# Generated by Django 4.2.10 on 2024-03-31 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_remove_employeeposition_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAchieved',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScorePattern',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('score_allotted', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.project')),
                ('score_achieved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee.scoreachieved')),
                ('score_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee.scorepattern')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('payment_proof', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee.employee')),
            ],
        ),
    ]
