# Generated by Django 4.2.10 on 2024-04-01 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.PROTECT, to='Employee.employee'),
            preserve_default=False,
        ),
    ]
