# Generated by Django 4.2.10 on 2024-04-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_join_date_alter_employee_resign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_level',
            field=models.IntegerField(default=0, help_text='This is used to show the employees different pages as of their positions.'),
        ),
    ]
