# Generated by Django 4.2.10 on 2024-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_emp_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_level',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='emp_level',
            field=models.IntegerField(default=0, help_text='This is used to show the employees different pages as of their positions.'),
        ),
    ]
