# Generated by Django 4.2.10 on 2024-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_remove_employee_emp_level_employeeposition_emp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
