# Generated by Django 4.2.11 on 2024-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_employee_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(auto_now_add=True, default='2024-04-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='emp_level',
            field=models.IntegerField(default=3, help_text='This is used to show the employees different pages as of their positions.'),
        ),
    ]
