# Generated by Django 4.2.10 on 2024-03-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.TextField()),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('project_init_date', models.DateField()),
                ('user_agreement', models.FileField(upload_to='')),
                ('git_link', models.TextField()),
                ('project_team', models.CharField(max_length=20)),
                ('estimated_amount', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_update', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('update_base_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAchieved',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScorePattern',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('score_allotted', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.project')),
                ('score_achieved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.scoreachieved')),
                ('score_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.scorepattern')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('payment_proof', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Aspirants',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(default='submitted', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('application_final_verified_date', models.DateField(null=True)),
                ('resume', models.FileField(max_length=200, upload_to='resume/%Y/')),
                ('identity_proof', models.FileField(max_length=200, upload_to='identity/%Y/')),
                ('study_certificate', models.FileField(max_length=200, upload_to='study_certificate/%Y/')),
                ('experience_proof', models.FileField(max_length=200, null=True, upload_to='experience_proof/%Y/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
