# Generated by Django 4.2.10 on 2024-03-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeposition',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='project',
        ),
        migrations.RemoveField(
            model_name='score',
            name='project',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_achieved',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_pattern',
        ),
        migrations.RemoveField(
            model_name='team',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='update_base_project',
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='root_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Home.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_init_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_agreement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeePosition',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='ScoreAchieved',
        ),
        migrations.DeleteModel(
            name='ScorePattern',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
