# Generated by Django 4.2.10 on 2024-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
