# Generated by Django 4.2.11 on 2024-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_project_project_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirants',
            name='aspirant_character_by_tm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aspirants',
            name='experience_proof',
            field=models.FileField(max_length=200, null=True, upload_to='experience_proof/'),
        ),
        migrations.AlterField(
            model_name='aspirants',
            name='identity_proof',
            field=models.FileField(max_length=200, upload_to='identity/'),
        ),
        migrations.AlterField(
            model_name='aspirants',
            name='resume',
            field=models.FileField(max_length=200, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='aspirants',
            name='study_certificate',
            field=models.FileField(max_length=200, upload_to='study_certificate/'),
        ),
    ]
